### PR TITLE
Add support for Discord Development

### PR DESCRIPTION
**Pull request by ChickenDevs**

### CODE REVIEW

**Comment by MrAugu** [comment]
What is that version of discord? The desktop version of discord testing works using "Experiments" - and it works just fine, I don't see the purpose of this unless you can provide more details.

**Comment by ChickenDevs** [comment]
I personally use Discord Development, and it wont work for me.

**Comment by ChickenDevs** [comment]
Download links:
Windows: https://discord.com/api/downloads/distributions/app/installers/latest?channel=development&platform=win&arch=x86
Mac: https://discord.com/api/download/development?platform=osx
Linux deb: https://discord.com/api/download/development?platform=linux&format=deb
Linux tar.gz: https://discord.com/api/download/development?platform=linux&format=tar.gz

**Comment by cwkhawand** [comment]
Make sure to resolve the branch conflicts first.
I'll close this PR, please open a new pull request with the new files.

**Pull request closed without merging**
